### ISSUE TITLE
argon-shutdown.sh Missing

### ISSUE THREAD

**Issue by PixelBully** [JeffCurless/argoneon#27]
The installer calls this:

# Argon Shutdown script
sudo curl -L $ARGONDOWNLOADSERVER/argon-shutdown.sh -o $shutdownscript --silent
sudo chmod 755 $shutdownscript

But all it gets is a 404: Not Found meaning the box cannot be shutdown by pressing the power button.

**Comment by OptimusGREEN** [comment]
I'm guessing this is resolved as my box shutdown when holding for 3 seconds

**Comment by OptimusGREEN** [comment]
Yeah I think have a single config file is a good idea. out of interest, how do I restart the service? I couldnt see it in systemd/system but wasn't really sure where to look.

**Comment by JeffCurless** [comment]
You should.  There is an attempt to re-read the config files on every loop but I'm not 100% sure that actually works properly.  Hence why I want to redo everything... I don't like the multiple config files, nor the multiple services...

Really want to fix up the library that is used to communicate with the OLED as I have a few projects I want to use the same type of OLED on.
