### ISSUE TITLE
Feature Request: cli commands

### ISSUE THREAD

**Issue by OptimusGREEN** [JeffCurless/argoneon#29]
It would be really nice to have some cli commands to show the info that argon script sees as well as instant fan speed command. Some thing like argoncmd --fan 30 and argoncmd --info.

**Comment by JeffCurless** [comment]
argon-status does some of this (i.e. reports that will be displayed on the OLED

**Comment by OptimusGREEN** [comment]
Nice one, I'll check it out

**Comment by JeffCurless** [comment]
Minor typo was just fixed.

**Comment by JeffCurless** [comment]
massive update to argon-status, included command line switches for limiting data fetching.

**Comment by OptimusGREEN** [comment]
Excellent work!
