### ISSUE TITLE
OLED cycle doesn't go to screensaver

### ISSUE THREAD

**Issue by sobirjon001** [JeffCurless/argoneon#61]
Hello I'm a new Argon Eon case owner and just have installed your util. Issue I have here is that OLED screen cycles indefinitely and never goes to screensaver.
Here are my /etc/argoneon.conf
```bash
[General]
temperature = C
debug = N

[OLED]
screenduration = 10
screensaver = 80
screenlist = clock cpu storage bandwidth ram temp ip
enabled = Y

[CPUFan]
45.0 = 25
50.0 = 30
55.0 = 55
60.0 = 100

[HDDFan]
38.0 = 25
40.0 = 50
44.0 = 60
46.0 = 80
48.0 = 90
50.0 = 100
```

**Comment by JeffCurless** [comment]
Actually it does, the issue is that the value for screensaver needs to be "LESS" than the value for screenduration, so

`screenduration=40
screensaver=30`

Should display the screen for 10 seconds, sleep for 30 then display the next screen

**Comment by JeffCurless** [comment]
Updated code to have a default value that automatically enables the screen saver,
