### ISSUE TITLE
Add Raspberry Pi OS (bookworm) support

### ISSUE THREAD

**Issue by ACasset** [JeffCurless/argoneon#63]
Hello,

Having recently acquired an Argon Eon, I installed the latest version of Raspberry Pi OS lite (bookworm), and the script hangs on the "login through serial port" UI.

I managed to make it work by changing [line 76 of the argoneon.sh script](https://github.com/JeffCurless/argoneon/blob/b57f9d735a9f7102f26ae70aca5a85ed14530175/argoneon.sh#L76) to this:
`elif $(echo ${pretty_name} | grep -q -F -e 'Debian' -e 'bookworm' /etc/os-release &> /dev/null); [ $? -eq 0 ]`

I know this isn't the right way to fix the issue, but my point is that by tricking the script, I was able to complete the install, and both `argon-config` and `argon-status` commands seem to work correctly (I never had an Argon Eon before, I don't know if there are other relevant commands).

EDIT: The `argon-config` has no option for fan control nor OLED.

Is there a way you could add a clean support of the bookworm version?

For reference, the content of my `/etc/os-release` file:
```
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

Maybe relying on the `/etc/rpi-issue` file might help?
```
Raspberry Pi reference 2023-12-11
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 2acf7afcba7d11500313a7b93bb55a2aae20b2d6, stage2
```

The "reference" date matches the release date of the OS from the Raspberry Pi Imager.
![image](https://github.com/JeffCurless/argoneon/assets/39308904/8cc94ead-f3ab-4a5e-a202-75e4bcd15af1)

Thanks for your work!

**Comment by JeffCurless** [comment]
Already fixed in the latest kit... I match for bookworm.  The real solution is to create a package...
