### ISSUE TITLE
Use `python3-rpi-lgpio` instead of `python3-rpi.gpio` on Bookworm

### ISSUE THREAD

**Issue by Jamie96ITS** [JeffCurless/argoneon#66]
I'm running these scripts on a RPi4, on Raspbian Bookworm.

I was investigating why the power button didn't seem to shut down and ran into this little issue:

```Aug 09 14:26:42 eon systemd[1]: Started argononed.service - Argon One Fan and Button Service.
Aug 09 14:26:42 eon python3[1977]: Exception in thread Thread-1 (shutdown_check):
Aug 09 14:26:42 eon python3[1977]: Traceback (most recent call last):
Aug 09 14:26:42 eon python3[1977]:   File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
Aug 09 14:26:42 eon python3[1977]:     self.run()
Aug 09 14:26:42 eon python3[1977]:   File "/usr/lib/python3.11/threading.py", line 975, in run
Aug 09 14:26:42 eon python3[1977]:     self._target(*self._args, **self._kwargs)
Aug 09 14:26:42 eon python3[1977]:   File "/etc/argon/argononed.py", line 79, in shutdown_check
Aug 09 14:26:42 eon python3[1977]:     GPIO.wait_for_edge(PIN_SHUTDOWN, GPIO.RISING)
Aug 09 14:26:42 eon python3[1977]: RuntimeError: Error waiting for edge
```

Apparently `python3-rpi.gpio` [does not work on Bookworm (or RPi5)](https://forums.raspberrypi.com/viewtopic.php?t=369751#p2216457), and needs to be replaced with `python3-rpi-lgpio`, possibly by breaking Bookworm out into its own check unless the library is compatible with previous Raspbian versions(unknown by me).

https://github.com/JeffCurless/argoneon/blob/7f40ee15973dbc840a3ec750ea21074b7a64d79b/argoneon.sh#L76-L80

So far this fix works for me, so I thought I'd share it upstream.

**Comment by JeffCurless** [comment]
Thanks for the code update!
