### ISSUE TITLE
Minor Typo

### ISSUE THREAD

**Issue by rodneyshupe** [JeffCurless/argoneon#7]
Thank you for fixing the "Bandwidh" -> "Bandwidth" but the "U" in utilization should also be capitalized to create consistency with the Argon scripts.

**Comment by JeffCurless** [comment]
Thanks!  Just updated.

**Comment by rodneyshupe** [comment]
You are faster than I could put in the pull request.  I figured that would be better than sending you a bunch of requests in the forum. 

Rodney (aka Zarquon)
